/*
** ###################################################################
**     THIS MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Project   : Stop_Mode_QG
**     Processor : MC9S08QG8CPB
**     Version   : Bean 01.216, Driver 01.00, CPU db: 2.87.068
**     Datasheet : MC9S08QG8 Rev. 0.09 09/9/2005
**     Date/Time : 10/17/2005, 12:10 PM
**     Abstract  :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents  :
**         Function "MCU_init" initializes selected peripherals
**
**     (c) Copyright UNIS, spol. s r.o. 1997-2005
**     UNIS, spol s r.o.
**     Jundrovska 33
**     624 00 Brno
**     Czech Republic
**     http      : www.processorexpert.com
**     mail      : info@processorexpert.com
** ###################################################################
*/

#include <MC9S08QG8.h>                 /* I/O map */

unsigned char hour = 0;
unsigned char min = 0;
unsigned char sec = 0;

/*
** ===================================================================
**     Method      :  MCU_init (bean MC9S08QG8_16)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  /* ### MC9S08QG8_16 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /*  System clock initialization */
  /* SOPT1: COPE=0,COPT=0,STOPE=1,X,X,X,BKGDPE=1,RSTPE=0 */
  SOPT1 = 0x32;//0x30                                      
  /* SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=0,BGBE=0 */
  SPMSC1 = 0x18;                                      
  /* SPMSC2: PDF=0,PPDF=0,PPDACK=0,PDC=0,PPDC=0 */
  SPMSC2 = 0x00;                                      
  /* SPMSC3: LVDV=0,LVWV=0 */
  SPMSC3 &= (unsigned char)~0x30;                              
  /* ICSC1: CLKS=0,RDIV=0,IREFS=1,IRCLKEN=0,IREFSTEN=0 */
  ICSC1 = 0x04;                        /* Initialization of the ICS control register 1 */
  /* ICSC2: BDIV=1,RANGE=0,HGO=0,LP=0,EREFS=0,ERCLKEN=0,EREFSTEN=0 */
  ICSC2 = 0x40;                        /* Initialization of the ICS control register 2 */
  /* Common initialization of the write once registers */
  /* SOPT2: COPCLKS=0,IICPS=0,ACIC=0 */
  SOPT2 = 0x00;  //siempre cero                                    

  /* Common initialization of the CPU registers */
  /* PTADD: PTADD5=0 */
  PTADD &= (unsigned char)~0x20;                              
  /* PTAPE: PTAPE5=1 */
  PTAPE |= (unsigned char)0x20;                               
  /* PTASE: PTASE5=1,PTASE4=1,PTASE3=1,PTASE2=1,PTASE1=1,PTASE0=1 */
  PTASE |= (unsigned char)0x3F;                               
  /* PTBSE: PTBSE7=1,PTBSE6=1,PTBSE5=1,PTBSE4=1,PTBSE3=1,PTBSE2=1,PTBSE1=1,PTBSE0=1 */
  PTBSE = 0xFF;                                      
  /* PTADS: PTADS5=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 */
  PTADS = 0x00;                                      
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
  PTBDS = 0x00;                                      
  /* ### Init_COP init code */
  SRS = 0xFF;                          /* Clear WatchDog counter */

  /* ### Init_IRQ init code */
  /* ** Initialize pin PTA5_IRQ_TCLK_RESET ** */
  /* IRQSC: IRQIE=0 */
  IRQSC &= (unsigned char)~0x02;       /* Disable IRQ Interrupt */
  /* IRQSC: IRQPE=1 */
  IRQSC |= (unsigned char)0x10;                               
  /* IRQSC: IRQIE=1 */
  IRQSC |= (unsigned char)0x02;                               
  /* ### Init_GPIO init code */
  /* PTBD: PTBD7=1,PTBD6=1 */
  PTBD |= (unsigned char)0xF0;                               
  /* PTBDD: PTBDD7=1,PTBDD6=1 */
  PTBDD |= (unsigned char)0xF0;                               
  /* ### */
  asm CLI;                             /* Enable interrupts */
} /*MCU_init*/


///*
//** ===================================================================
//**     Method      :  MCU_init (bean MC9S08QG8_16)
//**
//**     Description :
//**         Device initialization code for selected peripherals.
//** ===================================================================
//*/
//void MCU_init_RTI(void)
//{
//  /* ### MC9S08QG8_16 "Cpu" init code ... */
//  /*  PE initialization code after reset */
//  /*  System clock initialization */
//  /* SOPT1: COPE=0,COPT=1,STOPE=1,X,X,X,BKGDPE=1,RSTPE=1 */
//  SOPT1 = 0x73;                                      
//  /* SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 */
//  SPMSC1 = 0x1C;                                      
//  /* SPMSC2: PDF=0,PPDF=0,PPDACK=0,PDC=0,PPDC=0 */
//  SPMSC2 = 0x00;                                      
//  /* SPMSC3: LVDV=0,LVWV=0 */
//  SPMSC3 &= (unsigned char)~0x30;                              
//  /* ICSC1: CLKS=0,RDIV=2,IREFS=1,IRCLKEN=0,IREFSTEN=0 */
//  ICSC1 = 0x14;                        /* Initialization of the ICS control register 1 */
//  /* ICSC2: BDIV=0,RANGE=0,HGO=0,LP=0,EREFS=0,ERCLKEN=0,EREFSTEN=0 */
//  ICSC2 = 0x00;                        /* Initialization of the ICS control register 2 */
//  /* Common initialization of the write once registers */
//  /* SOPT2: COPCLKS=0,IICPS=0,ACIC=0 */
//  SOPT2 = 0x00;                                      
//
//  /* Common initialization of the CPU registers */
//  /* PTASE: PTASE5=1,PTASE4=1,PTASE3=1,PTASE2=1,PTASE1=1,PTASE0=1 */
//  PTASE |= (unsigned char)0x3F;                               
//  /* PTBSE: PTBSE7=1,PTBSE6=1,PTBSE5=1,PTBSE4=1,PTBSE3=1,PTBSE2=1,PTBSE1=1,PTBSE0=1 */
//  PTBSE = 0xFF;                                      
//  /* PTADS: PTADS5=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 */
//  PTADS = 0x00;                                      
//  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
//  PTBDS = 0x00;                                      
//  /* ### Init_RTI init code */
//  /* SRTISC: RTIF=0,RTIACK=0,RTICLKS=0,RTIE=1,RTIS2=1,RTIS1=1,RTIS0=1 */
//  SRTISC = 0x17;                                      
//  /* ### Init_COP init code */
//  SRS = 0xFF;                          /* Clear WatchDog counter */
//
//  /* ### Init_GPIO init code */
//  /* PTBD: PTBD7=1,PTBD6=1,PTBD5=1 */
//  PTBD |= (unsigned char)0xF0;                               
//  /* PTBPE: PTBPE7=0,PTBPE6=0,PTBPE5=0 */
//  PTBPE &= (unsigned char)~0xE0;                              
//  /* PTBDD: PTBDD7=1,PTBDD6=1,PTBDD5=1 */
//  PTBDD |= (unsigned char)0xF0;                               
//  /* ### */
//  asm CLI;                             /* Enable interrupts */
//} /*MCU_init*/
//
///*
//** ===================================================================
//**     Interrupt handler : Virq_isr
//**
//**     Description :
//**         User interrupt service routine. 
//**     Parameters  : None
//**     Returns     : Nothing
//** ===================================================================
//*/
//__interrupt void Virq_isr(void)
//{
//    IRQSC_IRQACK=1;				/*Clears IRQ flag*/
//
//}
///* end of Virq_isr */
//
///*
//** ===================================================================
//**     Interrupt handler : Vrti_isr
//**
//**     Description :
//**         User interrupt service routine. 
//**     Parameters  : None
//**     Returns     : Nothing
//** ===================================================================
//*/
//__interrupt void Vrti_isr(void)
//{
//     SRTISC_RTIACK = 1;  /* Acknowledges RTI flag*/
//
//    if(hour == 24){
//    
//        hour = 0;                    /* Resets hour counter*/
//    
//    }if (min == 60){
//    
//        hour++;                      /* Increases hour counter*/
//        min = 0;                     /* Resets minute counter*/
//        //PTBD_PTBD6 = ~PTBD_PTBD6;    /* toggle hour LED */
//    
//    }if(sec == 60){
//    
//        min++;                       /* Increases minutes counter*/
//        sec = 0;                     /* Resets seconds counter*/
//        //PTBD_PTBD5 = ~PTBD_PTBD5;    /* toggle minute LED */
//                                     
//    }else{                           
//        
//        sec++;                       /* Increases seconds counter*/
//        //PTBD_PTBD4 = ~PTBD_PTBD4;    /* toggle seconds LED */ 
//                                      
//    }                                
//
//
//
//}
///* end of Vrti_isr */
//
///* Initialization of the CPU registers in FLASH */
//
///* NVPROT: FPS=0x7F,FPDIS=1 */
////const volatile NVPROTSTR _NVPROT @0x0000FFBD = { 0xFF };
//
///* NVOPT: KEYEN=0,FNORED=1,SEC01=1,SEC00=0 */
////const volatile NVOPTSTR _NVOPT @0x0000FFBF = { 0x7E };
//
//
//
//extern void _Startup(void);
//
///* Interrupt vector table */
//#define UNASSIGNED_ISR 0xFFFF          /* unassigned interrupt service routine */
//
//void (* const _vect[])() @0xFFD0 = {   /* Interrupt vector table */
//         Vrti_isr,                     /* Int.no.  0 Vrti (at FFD0)                  Used */
//         UNASSIGNED_ISR,               /* Int.no.  1 Reserved2 (at FFD2)             Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  2 Reserved3 (at FFD4)             Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  3 Vacmp (at FFD6)                 Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  4 Vadc (at FFD8)                  Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  5 Vkeyboard (at FFDA)             Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  6 Viic (at FFDC)                  Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  7 Vscitx (at FFDE)                Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  8 Vscirx (at FFE0)                Unassigned */
//         UNASSIGNED_ISR,               /* Int.no.  9 Vscierr (at FFE2)               Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 10 Vspi (at FFE4)                  Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 11 Vmtim (at FFE6)                 Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 12 Reserved13 (at FFE8)            Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 13 Reserved14 (at FFEA)            Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 14 Reserved15 (at FFEC)            Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 15 Reserved16 (at FFEE)            Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 16 Vtpmovf (at FFF0)               Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 17 Vtpmch1 (at FFF2)               Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 18 Vtpmch0 (at FFF4)               Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 19 Reserved20 (at FFF6)            Unassigned */
//         UNASSIGNED_ISR,               /* Int.no. 20 Vlvd (at FFF8)                  Unassigned */
//         Virq_isr,                     /* Int.no. 21 Virq (at FFFA)                  Used */
//         UNASSIGNED_ISR,               /* Int.no. 22 Vswi (at FFFC)                  Unassigned */
//         //_Startup                      /* Int.no. 23 Vreset (at FFFE)                Reset vector */
// };
//
//


/* END */

/*
** ###################################################################
**
**     This file was created by UNIS Processor Expert 2.97 BETA [03.71]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
